# always required when using docker
sudo: required

services:
  # always required when using docker
  - docker

env:
  global:
    # allow access to git sha in build/deploy to be able to tag image correctly
    - SHA=$(git rev-parse HEAD)
    # configure gcloud cli not to display prompts
    - CLOUDSDK_CORE_DISABLE_PROMPTS=1

before_install:
  # from encryption of service-account.json (gcloud credentials)
  -  openssl aes-256-cbc -K $encrypted_0c35eebf403c_key -iv $encrypted_0c35eebf403c_iv -in service-account.json.enc -out service-account.json -d

  # need to install google cloud sdk for the build
  - curl https://sdk.cloud.google.com | bash > /dev/null;
  - source $HOME/google-cloud-sdk/path.bash.inc
  - gcloud components update kubectl
  # equivalent to IAM system in AWS. Need to activate and pass credentials stored in file
  - gcloud auth activate-service-account --key-file service-account.json
  # remove encrypted file after use
  - rm -f service-account.json
  # set the project using the id from gcloud
  - gcloud config set project fibonacci-kubernetes-250120
  - gcloud config set compute/zone us-east1-c	
  - gcloud container clusters get-credentials fibonacci-cluster

  # login to docker via cli
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  # build a test image
  - docker build -t guygaver/fibonacci-client-test -f ./client/Dockerfile.dev ./client

script:
  # run the tests in an image
  - docker run -e CI=true guygaver/fibonacci-client-test npm run test

deploy:
  # tell Travis for deployment we want to run a custom script
  provider: script
  script: bash ./deploy.sh
  on:
    branch: master