apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: talesofadeskyogi-com-tls
spec:
  secretName: talesofadeskyogi-com
  issuerRef:
    name: letsencrypt-prod # relates to Issuer.yaml private secret ref
    kind: ClusterIssuer
  commonName: talesofadeskyogi.com # what will be shown in the SSL cert in the browser
  dnsNames: # list of all different domains associated with certificate
    - talesofadeskyogi.com
    - www.talesofadeskyogi.com
  acme:
    config:
      - http01: 
          ingressClass: nginx
        domains: 
          - talesofadeskyogi.com
          - www.talesofadeskyogi.com