apiVersion: apps/v1
kind: Deployment
metadata:
  name: fibonacci-server-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      component: api
  template:
    metadata:
      labels:
        component: api
    spec:
      containers:
        - name: fibonacci-server
          image: guygaver/fibonacci-node-server
          ports:
            - containerPort: 5000
          env:
            - name: REDIS_HOST
              value: fibonacci-redis-cluster-ip-service
            - name: REDIS_PORT
              value: '6379'
            - name: PGUSER
              value: postgres
            - name: PGHOST
              value: fibonacci-postgres-cluster-ip-service
            - name: PGPORT
              value: '5432'
            - name: PGDATABASE
              value: postgres
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: pgpassword
                  key: PGPASSWORD