apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress-service
  annotations:
    kubernetes.io/ingress.class: nginx # telling kubernetes create ingress controller based on ingress project
    nginx.ingress.kubernetes.io/rewrite-target: /$1 # configure how copy of nginx behaves, if we match route then rewrite request
    certmanager.k8s.io/cluster-issuer: 'letsencrypt-prod' # inform ingress that we are expecting a certificate designated by issuer name (cert/issuer)
    nginx.ingress.kubernetes.io/ssl-redirect: 'true' # reconfigure nginx to only allow access via https
spec:
  tls: # configure tls
    - hosts:
        - talesofadeskyogi.com
        - www.talesofadeskyogi.com
      secretName: talesofadeskyogi-com
  rules:
    - host: talesofadeskyogi.com
      http:
        paths:
          - path: /?(.*)
            backend:
              serviceName: fibonacci-client-ip-service
              servicePort: 3000
          - path: /api/?(.*)
            backend:
              serviceName: fibonacci-server-ip-service
              servicePort: 5000
    - host: www.talesofadeskyogi.com
      http:
        paths:
          - path: /?(.*)
            backend:
              serviceName: fibonacci-client-ip-service
              servicePort: 3000
          - path: /api/?(.*)
            backend:
              serviceName: fibonacci-server-ip-service
              servicePort: 5000